// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnoxtpcjwifaquokfohj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFub3h0cGNqd2lmYXF1b2tmb2hqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1NzgzOTcsImV4cCI6MjA3NzE1NDM5N30.QKP7mjxm3nkc6kGquyGk5ziBy0BntH3r7jswS-OzAAA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});